# -*- coding: utf-8 -*-
"""datascraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhr3zZz6PKSP5YgO0qMaxl05UggHDkNe
"""

from bs4 import BeautifulSoup
import pandas as pd
import requests

url = 'https://www.scrapethissite.com/pages/forms/?page_num=2'
page = requests.get(url)

soup = BeautifulSoup(page.text,'html')

table = soup.find_all('table', class_ = 'table')

table

table_headers = soup.find_all('th')
table_headers = [title.text.strip() for title in table_headers]
print(table_headers)

table_rows = []
all_rows = soup.find_all('tr')

for data in all_rows[1:]:
    row_data = data.find_all('td')
    row_data = [cell.text.strip() for cell in row_data]
    table_rows.append(row_data)

table_rows

df = pd.DataFrame(table_rows, columns=table_headers)

df

stats_csv = df.to_csv(r'hockey.csv', index=False)

stats_reader = pd.read_csv('hockey.csv')
stats_reader

